// happy.js
var lastHoveredButton = "btn-primary"; // Agrega esta línea

var mensajesHappy = [
    "Que cada paso que des esté guiado por la luz divina. 🚶‍♂️💡",
    "Que la paz de Dios te acompañe hoy y siempre. 💖🌟",
    "Cada día es una página en blanco. Escribe una historia increíble llena de risas, amor y logros. ¡Hoy es tu día para brillar! 💫✨",
    "Recuerda: cada nube tiene un borde plateado. ¡Que las pequeñas alegrías iluminen tu día y te hagan sonreír! 🌈😁",
    "Eres como un rayo de sol en un día nublado. Tu positividad ilumina los corazones a tu alrededor. ☀️💛",
    "La vida es corta, así que come el postre primero, ríe demasiado y nunca dejes de ser una chispa de felicidad. 🍰😂",
    "No cuentes los días, haz que los días cuenten. ¡Que hoy sea tan brillante y asombroso como tú eres! 🚀🌟",
    "La felicidad es una elección. Elige ser feliz hoy y deja que esa elección ilumine tu día y el de los demás. 😃💖",
    "Si la belleza fuera tiempo, ¡tú serías la eternidad! ⏳💖",
    "Eres como un 🌈 en un día lluvioso, llenando la vida de colores y alegría.",
    "Eres un ☀️ en los días grises, siempre trayendo calidez y luz a la vida.",
    "Si fueras un 🎨, serías la obra maestra más hermosa que mis ojos han visto.",
    "Eres como un 🍭, siempre endulzando los días con tu ternura y alegría.",
    "Si la perfección fuera un 💎, tú serías la joya más preciosa.",
    "Eres como un 📚 de cuentos de hadas, cada página de tu historia es mágica.",
    "Si cada pensamiento tuyo fuera una 🎈, llenarías el cielo de colores.",
    "Si la vida fuera un escenario, tú serías la ⭐ principal.",
    "Eres el sueño del que no se quiere despertar, la razón de mi sonrisa. 😊✨",
    "Eres inspiración, el motivo por el cual cada día es especial. 🌈💫",
    "Si la felicidad fuera un lugar, sería a tu lado. 🏡❤️",
    "🌞'Este es el día que el Señor hizo; regocijémonos y alegrémonos en él.' - Salmos 118:24",
    "🌈'Yo sé los planes que tengo para ustedes, planes para su bienestar y no para su mal, a fin de darles un futuro lleno de esperanza.' - Jeremías 29:11",
    "🌺 'Confíenle todas sus preocupaciones, porque él cuida de ustedes.' - 1 Pedro 5:7",
    "🌿 'Por lo tanto, no se preocupen por el día de mañana, pues el día de mañana traerá sus propias preocupaciones. A cada día le bastan sus propios problemas.' - Mateo 6:34",
    "🎨 'Porque somos hechura de Dios, creados en Cristo Jesús para hacer buenas obras, las cuales Dios dispuso de antemano a fin de que las pongamos en práctica.' - Efesios 2:10",
    "🌈 ¿Qué pequeños momentos te hacen feliz en la vida cotidiana?",
    "🌺 ¿Qué consejo te darías a ti mismo si pudieras volver al pasado?",
    "🌞 ¿Cómo te cuidas a ti mismo y recargas tus energías?",
    "🌍 ¿Cuál es tu propósito en la vida y cómo contribuyes al mundo?",
    "😌 ¿Cómo encuentras la paz interior en tiempos difíciles?",
    "🌱 ¿Cuál es tu mayor inspiración en la vida?",
    "🐧 Los pingüinos tienen solo un compañero de vida y pueden hacer regalos de piedras para expresar su amor.",
    "🌈 Los arcoíris son círculos completos, pero generalmente solo vemos la mitad debido a la línea del horizonte.",
    "🌊 El 70% de la superficie de la Tierra está cubierta por océanos.",
    "🦘 Los canguros no pueden saltar hacia atrás, solo hacia adelante.",
    "🌐 El inventor de Internet, Sir Tim Berners-Lee, eligió '//' para los primeros sitios web porque era fácil de recordar.",
    "🦉 Los búhos pueden girar sus cabezas hasta 270 grados sin mover sus cuerpos.",
    "🚀 El sonido no puede viajar a través del espacio porque es un vacío.",
    "🌍 En la Antártida, hay un lago que tiene una capa de agua líquida bajo una capa de hielo, llamado Lago Vostok.",
    "🎵 Las ballenas jorobadas tienen canciones complejas y cada grupo canta una versión ligeramente diferente.",
    "🌞 La Tierra tarda aproximadamente 365.25 días en orbitar alrededor del sol.",
    "🌽 El maíz es una de las pocas verduras que nunca cambian de forma cuando se cocinan.",
    "🦈 Los tiburones no tienen huesos; sus esqueletos están hechos de cartílago.",
    "😂 ¿Qué hace una abeja en el gimnasio?🏋️‍♀️ ¡Zum-ba!",
    "👻 ¿Qué hace una abeja en el gimnasio?🍯 ¡Abe-jercicios!",
    "🐍 ¿Qué hace una serpiente en el gimnasio?🏋️ ¡Sssss-entadillas!",
    "🌈 El Unicornio y la Mariposa: Un día, un unicornio y una mariposa se encontraron en el bosque. Juntos, descubrieron un arcoíris mágico que les llevó a un mundo lleno de aventuras y sueños.",
    "🚀 Viaje a las Estrellas: Sara construyó una nave espacial con cajas y sueños. Con su gato cósmico, emprendió un viaje a las estrellas donde descubrieron planetas brillantes y amistades intergalácticas.",
    "🌌 El Deseo de la Estrella:En una noche estrellada, una estrella fugaz escuchó el deseo de Lucas de tener un día lleno de risas. Al día siguiente, todo el mundo a su alrededor comenzó a reír, incluso las flores.",
    "🎈 El Globo de los Sueños: Juan ató sus sueños a un globo y lo dejó volar. Mientras subía, el globo se llenó de colores y al llegar al cielo, sus sueños se hicieron realidad.",
    "🌟 Lucía y las Luciérnagas: Lucía siguió a las luciérnagas en una noche oscura. Descubrió que cada destello llevaba consigo un deseo, y así aprendió a encontrar luz en la oscuridad.",
    "🍮 Cómo la gelatina azul que luce verde en la atmósfera de Aristóteles mientras come ensalada de flores negras porque se ensucia la frente de mango. Esta vez sí tenía algo que decir. ✨Un poema✨",
    "🌊 Bajo la luna plateada,🌙 el mar susurra secretos.🐚 Conchas guardan historias,📜 en arenas de sueños completos.",
    "🌄 Amanecer dorado, ☀️ ilumina nuevos caminos. 🌺 Flores despiertan,🌷 con promesas y destinos.",
    "🍬 Los copitos de dulce son conocidos por su sabor dulce y se asocian comúnmente con la alegría y la felicidad.",
    "🎉 Muchos copos de dulce están vinculados a celebraciones y eventos festivos, como la Navidad.",
    "🎁 En ocasiones, los copos de dulce se comparten o regalan, simbolizando generosidad y afecto.",
    "🌈 La variedad de colores en los copos de dulce puede representar la diversidad y añadir un toque de alegría visual.",
    "💖 Algunos copos de dulce son delicados y frágiles, lo que puede simbolizar la delicadeza de las relaciones y momentos especiales."
];

